<?php
// generate_payslip_pdf.php
session_start();
// Check if user is logged in
if (!isset($_SESSION['user_id'])) {
    header('Location: index.php');
    exit();
}

// Database connection
require_once 'includes/db_config.php';

// Set timezone to Manila
date_default_timezone_set('Asia/Manila');

// Load Dompdf library
require_once 'vendor/autoload.php';

use Dompdf\Dompdf;
use Dompdf\Options;

// Get parameters from URL
$date_from = isset($_GET['date_from']) && !empty($_GET['date_from']) ? $_GET['date_from'] : null;
$date_to = isset($_GET['date_to']) && !empty($_GET['date_to']) ? $_GET['date_to'] : null;
$department = isset($_GET['department']) && !empty($_GET['department']) ? $_GET['department'] : null;

// If no date range provided, use current month
if (!$date_from || !$date_to) {
    $date_from = date('Y-m-01'); // First day of current month
    $date_to = date('Y-m-t'); // Last day of current month
}

// Get user details for footer
$user_id = $_SESSION['user_id'];
$stmt = $pdo->prepare("SELECT firstname, middlename, lastname, suffix FROM users WHERE id = :id");
$stmt->bindParam(':id', $user_id);
$stmt->execute();
$user = $stmt->fetch(PDO::FETCH_ASSOC);

// Format the display name for the generated by - using "Last, First M." format
$display_name = $user['lastname'] . ', ' . $user['firstname'];
if (!empty($user['middlename'])) {
    $display_name .= ' ' . substr($user['middlename'], 0, 1) . '.';
}
if (!empty($user['suffix'])) {
    $display_name .= ' ' . $user['suffix'];
}

// Get company settings
try {
    $settingsStmt = $pdo->query("SELECT * FROM company_settings WHERE id = 1");
    $company = $settingsStmt->fetch(PDO::FETCH_ASSOC);
    if (!$company) {
        $company = [
            'company_name' => 'OCP Construction',
            'company_address' => '123 Construction St., Building City, 1234',
            'company_phone' => '(123) 456-7890',
            'company_email' => 'info@ocpconstruction.com',
            'company_logo' => ''
        ];
    }
} catch (PDOException $e) {
    $company = [
        'company_name' => 'OCP Construction',
        'company_address' => '123 Construction St., Building City, 1234',
        'company_phone' => '(123) 456-7890',
        'company_email' => 'info@ocpconstruction.com',
        'company_logo' => ''
    ];
}

/**
 * Format employee name in "LAST, FIRST M. SUFFIX" format (all caps)
 */
function formatEmployeeName($firstname, $middlename, $lastname, $suffix) {
    $name = strtoupper($lastname . ', ' . $firstname);
    if (!empty($middlename)) {
        $name .= ' ' . strtoupper(substr($middlename, 0, 1)) . '.';
    }
    if (!empty($suffix)) {
        $name .= ' ' . strtoupper($suffix);
    }
    return $name;
}

/**
 * Format date to readable format (m/d/Y)
 */
function formatDate($dateStr) {
    if (empty($dateStr)) return '';
    return date('m/d/Y', strtotime($dateStr));
}

/**
 * Format time to 12-hour format
 */
function formatTimeTo12Hour($timeStr) {
    if (empty($timeStr)) return '--:--';
    return date('h:i:s A', strtotime($timeStr));
}

/**
 * Format currency
 */
function formatCurrency($amount) {
    return '' . number_format($amount, 2);
}

/**
 * Calculate late deduction based on minutes late and daily rate
 * Formula: (Daily Rate / 8 hours) / 60 * Late Minutes
 */
function calculateLateDeduction($daily_rate, $late_minutes) {
    if ($daily_rate <= 0 || $late_minutes <= 0) {
        return 0;
    }
    // Assuming 8-hour work day
    // Calculate per minute rate: (Daily Rate / 8 hours) / 60 minutes
    $per_minute_rate = ($daily_rate / 8) / 60;
    return $per_minute_rate * $late_minutes;
}

/**
 * Calculate overtime pay based on minutes overtime and daily rate
 * Formula: (Daily Rate / 8 hours) / 60 * Overtime Minutes
 */
function calculateOvertimePay($daily_rate, $overtime_minutes) {
    if ($daily_rate <= 0 || $overtime_minutes <= 0) {
        return 0;
    }
    // Assuming 8-hour work day
    // Calculate per minute rate: (Daily Rate / 8 hours) / 60 minutes
    $per_minute_rate = ($daily_rate / 8) / 60;
    return $per_minute_rate * $overtime_minutes;
}

/**
 * Get effective wage for an employee during a specific period
 * Checks wage_history for any wage changes during the period
 */
function getEffectiveWage($pdo, $employee_id, $period_start, $period_end) {
    try {
        // First, get the current wage from employee table
        $stmt = $pdo->prepare("SELECT daily_wage FROM employee WHERE id = :id");
        $stmt->execute([':id' => $employee_id]);
        $employee = $stmt->fetch(PDO::FETCH_ASSOC);
        $current_wage = floatval($employee['daily_wage'] ?? 0);
        
        // Check wage_history for any changes during this period
        $historyStmt = $pdo->prepare("
            SELECT new_wage, effectivity_date 
            FROM wage_history 
            WHERE employee_id = :employee_id 
            AND effectivity_date <= :period_end
            ORDER BY effectivity_date DESC 
            LIMIT 1
        ");
        
        $historyStmt->execute([
            ':employee_id' => $employee_id,
            ':period_end' => $period_end
        ]);
        
        $history = $historyStmt->fetch(PDO::FETCH_ASSOC);
        
        // If there's a wage change that took effect during or before this period, use that
        if ($history && strtotime($history['effectivity_date']) <= strtotime($period_end)) {
            return floatval($history['new_wage']);
        }
        
        return $current_wage;
        
    } catch (PDOException $e) {
        error_log("Error getting effective wage: " . $e->getMessage());
        return 0;
    }
}

/**
 * Get wage for a specific employee on a specific date
 */
function getEmployeeWageOnDate($pdo, $employee_id, $attendance_date) {
    try {
        $sql = "
            SELECT new_wage as daily_rate
            FROM wage_history
            WHERE employee_id = :employee_id
            AND effectivity_date <= :attendance_date
            ORDER BY effectivity_date DESC
            LIMIT 1
        ";
        
        $stmt = $pdo->prepare($sql);
        $stmt->bindParam(':employee_id', $employee_id);
        $stmt->bindParam(':attendance_date', $attendance_date);
        $stmt->execute();
        
        $result = $stmt->fetch(PDO::FETCH_ASSOC);
        
        if ($result && isset($result['daily_rate'])) {
            return floatval($result['daily_rate']);
        }
        
        // If no wage history found, get the current daily wage from employee table
        $stmt = $pdo->prepare("SELECT daily_wage FROM employee WHERE id = :id");
        $stmt->bindParam(':id', $employee_id);
        $stmt->execute();
        $current_wage = $stmt->fetch(PDO::FETCH_ASSOC);
        
        return $current_wage ? floatval($current_wage['daily_wage']) : 0.00;
        
    } catch(PDOException $e) {
        error_log("Error fetching wage for employee $employee_id on $attendance_date: " . $e->getMessage());
        return 0.00;
    }
}

/**
 * Get employee deductions effective during the specified period
 */
function getEmployeeDeductions($pdo, $employee_id, $period_start, $period_end) {
    $deductions = [];
    
    try {
        // Get all deductions that are effective during this period
        $stmt = $pdo->prepare("
            SELECT * FROM employee_deductions 
            WHERE employee_id = :employee_id
            AND (
                (effectivity_date BETWEEN :period_start AND :period_end)
                OR (effectivity_date <= :period_end AND effectivity_date IS NOT NULL)
            )
            AND (
                (from_date IS NULL AND to_date IS NULL)
                OR (from_date <= :period_end AND (to_date IS NULL OR to_date >= :period_start))
            )
            ORDER BY deduction_type, effectivity_date
        ");
        
        $stmt->execute([
            ':employee_id' => $employee_id,
            ':period_start' => $period_start,
            ':period_end' => $period_end
        ]);
        
        $deductions = $stmt->fetchAll(PDO::FETCH_ASSOC);
        
        // Group deductions by type and calculate total
        $grouped_deductions = [];
        foreach ($deductions as $deduction) {
            $type = $deduction['deduction_type'];
            if (!isset($grouped_deductions[$type])) {
                $grouped_deductions[$type] = [
                    'type' => $type,
                    'amount' => 0,
                    'items' => []
                ];
            }
            $grouped_deductions[$type]['amount'] += floatval($deduction['amount']);
            $grouped_deductions[$type]['items'][] = $deduction;
        }
        
        return array_values($grouped_deductions);
        
    } catch (PDOException $e) {
        error_log("Error getting employee deductions: " . $e->getMessage());
        return [];
    }
}

/**
 * Get deduction type display name
 */
function getDeductionTypeName($type) {
    $names = [
        'cash_advance' => 'CASH ADV',
        'sss_pag_ibig' => 'SSS/PAG-IBIG',
        'philhealth' => 'PHILHEALTH',
        'sss' => 'SSS',
        'pag_ibig' => 'PAG-IBIG',
        'withholding_tax' => 'WITHHOLDING TAX',
        'late' => 'LATE'
    ];
    
    return $names[$type] ?? strtoupper(str_replace('_', ' ', $type));
}

/**
 * Calculate work days between two dates (including ALL days)
 */
function calculateWorkDays($start_date, $end_date) {
    $work_days = 0;
    $current = strtotime($start_date);
    $end = strtotime($end_date);
    
    while ($current <= $end) {
        // Include ALL days (including Sundays)
        $work_days++;
        $current = strtotime('+1 day', $current);
    }
    
    return $work_days;
}

// Fetch attendance records grouped by employee
$attendance_by_employee = [];

try {
    $sql = "
        SELECT 
            a.*,
            e.employee_id as emp_code,
            e.firstname,
            e.middlename,
            e.lastname,
            e.suffix,
            e.daily_wage,
            e.position,
            e.id as employee_db_id
        FROM attendance a
        JOIN employee e ON a.employee_id = e.id
        WHERE a.attendance_date BETWEEN :date_from AND :date_to
        AND e.status = 'active'
    ";
    
    $params = [
        ':date_from' => $date_from,
        ':date_to' => $date_to
    ];
    
    // Apply department filter
    if ($department) {
        $sql .= " AND a.department = :department";
        $params[':department'] = $department;
    }
    
    $sql .= " ORDER BY e.lastname ASC, e.firstname ASC, a.attendance_date ASC";
    
    $attendanceStmt = $pdo->prepare($sql);
    $attendanceStmt->execute($params);
    $attendance_records = $attendanceStmt->fetchAll(PDO::FETCH_ASSOC);
    
    // Calculate work days
    $work_days = calculateWorkDays($date_from, $date_to);
    
    // Group records by employee and calculate detailed statistics
    foreach ($attendance_records as $record) {
        $employee_key = $record['employee_id'];
        
        if (!isset($attendance_by_employee[$employee_key])) {
            // Format employee name (ALL CAPS)
            $full_name = formatEmployeeName(
                $record['firstname'],
                $record['middlename'],
                $record['lastname'],
                $record['suffix']
            );
            
            $attendance_by_employee[$employee_key] = [
                'employee_id' => $record['employee_id'],
                'emp_code' => $record['emp_code'],
                'employee_name' => $full_name,
                'firstname' => $record['firstname'],
                'middlename' => $record['middlename'],
                'lastname' => $record['lastname'],
                'suffix' => $record['suffix'],
                'position' => $record['position'],
                'department' => $record['department'],
                'daily_wage' => 0, // Will be calculated as average
                'attendance' => [],
                'deductions' => [],
                'totals' => [
                    'days_present' => 0,
                    'days_halfday' => 0,
                    'days_absent' => 0,
                    'total_late_minutes' => 0,
                    'total_overtime_minutes' => 0,
                    'regular_days' => 0,
                    'total_hours_worked' => 0,
                    'total_late_deductions' => 0,
                    'total_overtime_pay' => 0,
                    'total_cash_advance' => 0,
                    'total_sss' => 0,
                    'total_pag_ibig' => 0,
                    'total_philhealth' => 0,
                    'total_deductions' => 0
                ],
                'present_dates' => [],
                'halfday_dates' => []
            ];
        }
        
        // Add record to employee
        $attendance_by_employee[$employee_key]['attendance'][] = $record;
        
        // Get wage for this specific date
        $daily_rate = getEmployeeWageOnDate($pdo, $record['employee_db_id'], $record['attendance_date']);
        
        // Calculate totals based on status
        $status = $record['status'] ?? 'Present';
        if ($status == 'Present') {
            $attendance_by_employee[$employee_key]['totals']['days_present']++;
            $attendance_by_employee[$employee_key]['totals']['regular_days']++;
            $attendance_by_employee[$employee_key]['present_dates'][] = $record['attendance_date'];
            
            // Calculate hours worked for this day
            if (!empty($record['check_in']) && !empty($record['check_out'])) {
                $check_in = strtotime($record['check_in']);
                $check_out = strtotime($record['check_out']);
                $hours_worked = ($check_out - $check_in) / 3600;
                // Subtract 1 hour for lunch break if both break times exist
                if (!empty($record['break_out']) && !empty($record['break_in'])) {
                    $hours_worked -= 1;
                }
                $attendance_by_employee[$employee_key]['totals']['total_hours_worked'] += $hours_worked;
            }
        } elseif ($status == 'Half Day') {
            $attendance_by_employee[$employee_key]['totals']['days_halfday']++;
            $attendance_by_employee[$employee_key]['totals']['regular_days'] += 0.5;
            $attendance_by_employee[$employee_key]['halfday_dates'][] = $record['attendance_date'];
            // Calculate half day hours (approximately 4 hours)
            $attendance_by_employee[$employee_key]['totals']['total_hours_worked'] += 4;
        }
        
        // Calculate late deduction
        $late_minutes = intval($record['late_time'] ?? 0);
        if ($late_minutes > 0) {
            $attendance_by_employee[$employee_key]['totals']['total_late_minutes'] += $late_minutes;
            $late_deduction = calculateLateDeduction($daily_rate, $late_minutes);
            $attendance_by_employee[$employee_key]['totals']['total_late_deductions'] += $late_deduction;
        }
        
        // Calculate overtime pay
        $overtime_minutes = intval($record['over_time'] ?? 0);
        if ($overtime_minutes > 0) {
            $attendance_by_employee[$employee_key]['totals']['total_overtime_minutes'] += $overtime_minutes;
            $overtime_pay = calculateOvertimePay($daily_rate, $overtime_minutes);
            $attendance_by_employee[$employee_key]['totals']['total_overtime_pay'] += $overtime_pay;
        }
    }
    
    // Calculate averages and get deductions for each employee
    foreach ($attendance_by_employee as $emp_key => $emp_data) {
        // Calculate average daily wage
        if ($emp_data['totals']['regular_days'] > 0) {
            // Get all wage history for this employee during the period to calculate average
            $total_wage_sum = 0;
            $days_counted = 0;
            
            foreach ($emp_data['attendance'] as $record) {
                if ($record['status'] == 'Present' || $record['status'] == 'Half Day') {
                    $daily_rate = getEmployeeWageOnDate($pdo, $record['employee_db_id'], $record['attendance_date']);
                    if ($record['status'] == 'Present') {
                        $total_wage_sum += $daily_rate;
                        $days_counted++;
                    } else {
                        $total_wage_sum += ($daily_rate / 2);
                        $days_counted += 0.5;
                    }
                }
            }
            
            $attendance_by_employee[$emp_key]['daily_wage'] = $days_counted > 0 ? $total_wage_sum / $days_counted : 0;
        } else {
            // If no present days, use the most recent wage
            $attendance_by_employee[$emp_key]['daily_wage'] = getEmployeeWageOnDate($pdo, $emp_data['employee_id'], $date_to);
        }
        
        // Get employee deductions
        $deductions = getEmployeeDeductions($pdo, $emp_data['employee_id'], $date_from, $date_to);
        
        // Separate deductions by type
        $cash_advance = 0;
        $sss = 0;
        $pag_ibig = 0;
        $philhealth = 0;
        
        foreach ($deductions as $deduction) {
            $type = $deduction['type'];
            $amount = $deduction['amount'];
            
            if ($type == 'cash_advance') {
                $cash_advance += $amount;
            } elseif ($type == 'sss') {
                $sss += $amount;
            } elseif ($type == 'pag_ibig') {
                $pag_ibig += $amount;
            } elseif ($type == 'philhealth') {
                $philhealth += $amount;
            }
        }
        
        $attendance_by_employee[$emp_key]['deductions'] = $deductions;
        $attendance_by_employee[$emp_key]['totals']['total_cash_advance'] = $cash_advance;
        $attendance_by_employee[$emp_key]['totals']['total_sss'] = $sss;
        $attendance_by_employee[$emp_key]['totals']['total_pag_ibig'] = $pag_ibig;
        $attendance_by_employee[$emp_key]['totals']['total_philhealth'] = $philhealth;
        
        // Calculate total deductions
        $total_deductions = $attendance_by_employee[$emp_key]['totals']['total_late_deductions'] + 
                           $cash_advance + $sss + $pag_ibig + $philhealth;
        $attendance_by_employee[$emp_key]['totals']['total_deductions'] = $total_deductions;
        
        // Sort dates
        sort($attendance_by_employee[$emp_key]['present_dates']);
        sort($attendance_by_employee[$emp_key]['halfday_dates']);
    }
    
} catch (PDOException $e) {
    die("Error fetching attendance records: " . $e->getMessage());
}

// Get the absolute file path for the logo
$logo_file_path = __DIR__ . '/img/logo/OCP.png';
// Convert to file:// URL for Dompdf
$logo_url = 'file://' . str_replace('\\', '/', $logo_file_path);

// Check if logo exists, if not, we'll just show text
$logo_html = '';
if (file_exists($logo_file_path)) {
    $logo_html = '<img src="' . $logo_url . '" class="company-logo" alt="OCP Logo" />';
} else {
    // Log that logo is missing (optional)
    error_log("Logo file not found at: " . $logo_file_path);
}

// Generate HTML for PDF with the template style
$html = '
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title>Payslips - OCP Construction</title>
    <style>
        @page {
            size: legal portrait;
            margin-left: 12px;
            margin-top: 12px;
            margin-bottom: -20px;
        }
        body {
            font-family: "Courier New", Courier, monospace;
            font-size: 8.5pt;
            line-height: 1.2;
            width: 100%;
            background: white;
        }
        .page {
            page-break-after: always;
            width: 100%;
        }
        .page:last-child {
            page-break-after: auto;
        }
        .payslip-row {
            width: 100%;
            margin-bottom: 5px;
        }
        .payslip {
            width: 48%;
            float: left;
            border: 2px solid #000;
            padding: 10px 8px;
            background-color: #fff;
            min-height: 350px;
        }
        .payslip-left {
            margin-right: 1%;
        }
        .payslip-right {
            margin-left: 1%;
        }
        .clearfix:after {
            content: "";
            display: table;
            clear: both;
        }
        .company-header {
            text-align: center;
            font-weight: bold;
            font-size: 15pt;
            margin-bottom: 2px;
            text-transform: uppercase;
            letter-spacing: 1px;
            display: flex;
            align-items: center;
            justify-content: center;
            border-bottom: 2px solid #2558be;
        }
        .company-logo {
            width: 50px;
            height: 50px;
            vertical-align: middle;
        }
        .company-name {
            display: inline-block;
            vertical-align: middle;
        }
        .company-address {
            font-size: 7pt;
        }
        .payslip-header {
            text-align: left;
            margin-bottom: 5px;
            padding-top: 3px;
            font-weight: bold;
            font-size: 11pt;
            text-align: center;
            text-transform: uppercase;
        }
        .payslip-period {
            text-align: left;
            font-size: 8pt;
            font-weight: bold;
            margin-bottom: 8px;
            border-bottom: 1px solid #000;
            padding-bottom: 5px;
            text-align: center;
        }
        .attendance-line {
            display: flex;
            justify-content: space-between;
            font-size: 9pt;
            margin-bottom: 5px;
            border-bottom: 1px solid #000;
            padding-bottom: 3px;
        }
        .earnings-title {
            font-weight: bold;
            font-size: 9pt;
            margin-top: 5px;
            margin-bottom: 5px;
        }
        .earnings-row {
            display: flex;
            justify-content: space-between;
            font-size: 9pt;
            margin-bottom: 5px;
            padding-left: 10px;
        }
        .deductions-title {
            font-weight: bold;
            font-size: 9pt;
            margin-top: 5px;
            margin-bottom: 5px;
        }
        .deductions-row {
            display: flex;
            justify-content: space-between;
            font-size: 8.5pt;
            margin-bottom: 5px;
            padding-left: 10px;
        }
        .total-deductions-row {
            display: flex;
            justify-content: space-between;
            font-weight: bold;
            font-size: 9pt;
            border-top: 1px solid #000;
            border-bottom: 1px solid #000;
            padding: 3px 0;
            margin: 8px 0;
        }
        .net-pay-row {
            display: flex;
            justify-content: space-between;
            font-weight: bold;
            font-size: 11pt;
            border-top: 2px solid #000;
            border-bottom: 2px solid #000;
            padding: 4px 0;
            margin: 5px 0;
            text-align: center;
        }
        .footer-line {
            display: flex;
            justify-content: space-between;
            font-size: 8pt;
            margin-top: 8px;
        }
        .date-label {
            text-align: right;
            float: right;
            margin-left: auto;
        }
        .deduction-label {
            color: red;
        }
        .overtime-label {
            color: green;
        }
        .present-label {
            color: green;
        }
        .halfday-label {
            color: orange;
        }
        .small-text {
            font-size: 7.5pt;
        }
        .page-break {
            page-break-after: always;
        }
    </style>
</head>
<body>';

// Format date range text
$date_range_text = 'ALL RECORDS';
if (!empty($date_from) && !empty($date_to)) {
    $date_from_formatted = date('m/d/Y', strtotime($date_from));
    $date_to_formatted = date('m/d/Y', strtotime($date_to));
    $date_range_text = strtoupper($date_from_formatted . ' - ' . $date_to_formatted);
}

// Calculate work days
$work_days = calculateWorkDays($date_from, $date_to);

// Check if there are any records
if (empty($attendance_by_employee)) {
    $html .= '<div style="text-align: center; padding: 40px; border: 1px dashed #000; font-family: monospace;">NO ATTENDANCE RECORDS FOUND FOR THE SELECTED CRITERIA</div>';
} else {
    // Prepare employee data for side-by-side layout
    $all_employee_data = [];
    
    foreach ($attendance_by_employee as $emp_key => $emp_data) {
        // Calculate basic pay
        $basic_pay = $emp_data['daily_wage'] * $emp_data['totals']['regular_days'];
        
        // Format present dates
        $formatted_present_dates = [];
        foreach ($emp_data['present_dates'] as $date) {
            $formatted_present_dates[] = formatDate($date);
        }
        
        // Calculate gross and net
        $gross = $basic_pay + $emp_data['totals']['total_overtime_pay'];
        $net = $gross - $emp_data['totals']['total_deductions'];
        
        $all_employee_data[] = [
            'name' => $emp_data['employee_name'],
            'branch' => strtoupper($emp_data['department'] ?: 'NO DEPARTMENT'),
            'present_days' => $emp_data['totals']['regular_days'],
            'working_days' => $work_days,
            'late_minutes' => $emp_data['totals']['total_late_minutes'],
            'overtime_minutes' => $emp_data['totals']['total_overtime_minutes'],
            'overtime_pay' => $emp_data['totals']['total_overtime_pay'],
            'basic_pay' => $basic_pay,
            'daily_rate' => number_format($emp_data['daily_wage'], 2),
            'late_deduction' => $emp_data['totals']['total_late_deductions'],
            'sss' => $emp_data['totals']['total_sss'],
            'pag_ibig' => $emp_data['totals']['total_pag_ibig'],
            'philhealth' => $emp_data['totals']['total_philhealth'],
            'cash_advance' => $emp_data['totals']['total_cash_advance'],
            'total_deductions' => $emp_data['totals']['total_deductions'],
            'gross' => $gross,
            'net' => $net
        ];
    }
    
    // Process employees in pairs for side-by-side layout
    $payslip_count = count($all_employee_data);
    
    for ($i = 0; $i < $payslip_count; $i += 2) {
        // Start a new page every 6 payslips (2 rows)
        if ($i > 0 && $i % 6 == 0) {
            $html .= '<div class="page-break"></div>';
        }
        
        $html .= '<div class="payslip-row clearfix">';
        
        // Left payslip
        if (isset($all_employee_data[$i])) {
            $p = $all_employee_data[$i];
            
            $html .= '
            <div class="payslip payslip-left">
                <div class="company-header">
                    ' . $logo_html . '
                    <span class="company-name">OCP CONSTRUCTION
                        <div class="company-address">Centro 1, Sanchez Mira, Cagayan</div>
                    </span>
                </div>
                <div class="payslip-header">' . htmlspecialchars($p['name']) . '</div>
                <div class="payslip-period">' . $date_range_text . '</div>
                
                <div class="attendance-line">
                    <strong>DAYS: ' . number_format($p['present_days'], 1).'(P)' . '/' . $p['working_days'] . '(WD)</strong>
                    <strong class="date-label">BRANCH: ' . htmlspecialchars($p['branch']) . '</strong>
                </div>
                
                <div class="earnings-title">EARNINGS</div>
                <div class="earnings-row">
                    <span>- BASIC: ' . number_format($p['present_days'], 1) . ' DAYS @ ' . $p['daily_rate'] . '/DAY</span>
                    <span>(' . number_format($p['basic_pay'], 2) . ')</span>
                </div>
                <div class="earnings-row">
                    <span>- <span class="overtime-label">OVERTIME: ' . $p['overtime_minutes'] . 'min</span></span>
                    <span>(' . number_format($p['overtime_pay'], 2) . ')</span>
                </div>
                
                <div class="deductions-title">DEDUCTIONS</div>
                <div class="deductions-row">
                    <span class="deduction-label">- LATE: ' . $p['late_minutes'] . 'min</span>
                    <span>(' . number_format($p['late_deduction'], 2) . ')</span>
                </div>
                <div class="deductions-row">
                    <span class="deduction-label">- SSS:</span>
                    <span>(' . number_format($p['sss'], 2) . ')</span>
                </div>
                <div class="deductions-row">
                    <span class="deduction-label">- PAG-IBIG:</span>
                    <span>(' . number_format($p['pag_ibig'], 2) . ')</span>
                </div>
                <div class="deductions-row">
                    <span class="deduction-label">- PHILHEALTH:</span>
                    <span>(' . number_format($p['philhealth'], 2) . ')</span>
                </div>
                <div class="deductions-row">
                    <span class="deduction-label">- CASH ADV:</span>
                    <span>(' . number_format($p['cash_advance'], 2) . ')</span>
                </div>
                
                <div class="total-deductions-row">
                    <span>TOTAL DEDUCTIONS:</span>
                    <span class="deduction-label">(' . number_format($p['total_deductions'], 2) . ')</span>
                </div>
                
                <div class="net-pay-row">
                    <span>NET PAY:</span>
                    <span>' . number_format($p['net'], 2) . '</span>
                </div>
                
                <div class="footer-line">
                    <span>RATE:' . $p['daily_rate'] . '</span>
                    <span class="date-label">DATE: ' . date('m/d/Y') . '</span>
                </div>
            </div>';
        } else {
            // Empty left payslip
            $html .= '<div class="payslip payslip-left" style="border: 2px dashed #ccc; background-color: #f9f9f9;"></div>';
        }
        
        // Right payslip
        if (isset($all_employee_data[$i + 1])) {
            $p = $all_employee_data[$i + 1];
            
            $html .= '
            <div class="payslip payslip-right">
                <div class="company-header">
                    ' . $logo_html . '
                    <span class="company-name">OCP CONSTRUCTION
                        <div class="company-address">Centro 1, Sanchez Mira, Cagayan</div>
                    </span>
                </div>
                <div class="payslip-header">' . htmlspecialchars($p['name']) . '</div>
                <div class="payslip-period">' . $date_range_text . '</div>
                
                <div class="attendance-line">
                    <strong>DAYS: ' . number_format($p['present_days'], 1) . '/' . $p['working_days'] . ' </strong>
                    <strong class="date-label">BRANCH: ' . htmlspecialchars($p['branch']) . '</strong>
                </div>
                
                <div class="earnings-title">EARNINGS</div>
                <div class="earnings-row">
                    <span>- BASIC: ' . number_format($p['present_days'], 1) . ' DAYS @ ' . $p['daily_rate'] . '/DAY</span>
                    <span>(' . number_format($p['basic_pay'], 2) . ')</span>
                </div>
                <div class="earnings-row">
                    <span>- <span class="overtime-label">OVERTIME: ' . $p['overtime_minutes'] . 'min</span></span>
                    <span>(' . number_format($p['overtime_pay'], 2) . ')</span>
                </div>
                
                <div class="deductions-title">DEDUCTIONS</div>
                <div class="deductions-row">
                    <span class="deduction-label">- LATE: ' . $p['late_minutes'] . 'min</span>
                    <span>(' . number_format($p['late_deduction'], 2) . ')</span>
                </div>
                <div class="deductions-row">
                    <span class="deduction-label">- SSS:</span>
                    <span>(' . number_format($p['sss'], 2) . ')</span>
                </div>
                <div class="deductions-row">
                    <span class="deduction-label">- PAG-IBIG:</span>
                    <span>(' . number_format($p['pag_ibig'], 2) . ')</span>
                </div>
                <div class="deductions-row">
                    <span class="deduction-label">- PHILHEALTH:</span>
                    <span>(' . number_format($p['philhealth'], 2) . ')</span>
                </div>
                <div class="deductions-row">
                    <span class="deduction-label">- CASH ADV:</span>
                    <span>(' . number_format($p['cash_advance'], 2) . ')</span>
                </div>
                
                <div class="total-deductions-row">
                    <span>TOTAL DEDUCTIONS:</span>
                    <span class="deduction-label">(' . number_format($p['total_deductions'], 2) . ')</span>
                </div>
                
                <div class="net-pay-row">
                    <span>NET PAY:</span>
                    <span>' . number_format($p['net'], 2) . '</span>
                </div>
                
                <div class="footer-line">
                    <span>RATE:' . $p['daily_rate'] . '</span>
                    <span class="date-label">DATE: ' . date('m/d/Y') . '</span>
                </div>
            </div>';
        } else {
            // Empty right payslip
            $html .= '<div class="payslip payslip-right" style="border: 2px dashed #ccc; background-color: #f9f9f9;"></div>';
        }
        
        $html .= '</div>'; // Close payslip-row
    }
}

$html .= '
</body>
</html>';

// Check if download or preview
if (isset($_GET['download']) || !isset($_GET['preview'])) {
    // Create PDF
    $options = new Options();
    $options->set('isHtml5ParserEnabled', true);
    $options->set('isPhpEnabled', true);
    $options->set('isRemoteEnabled', true);
    $options->set('defaultPaperSize', 'legal');
    $options->set('defaultPaperOrientation', 'portrait');
    $options->set('fontDir', __DIR__ . '/fonts/');
    $options->set('fontCache', __DIR__ . '/fonts/');
    $options->set('chroot', __DIR__);
    $options->set('dpi', 96);
    $options->set('defaultFont', 'Courier');

    $dompdf = new Dompdf($options);
    $dompdf->loadHtml($html);
    $dompdf->setPaper('legal', 'portrait');
    $dompdf->render();

    // Generate filename
    $filename = 'payslips_';
    $filename .= $date_from . '_to_' . $date_to;
    if ($department) {
        $filename .= '_' . preg_replace('/[^a-zA-Z0-9]/', '_', $department);
    }
    $filename .= '.pdf';

    // Output PDF
    $dompdf->stream($filename, array('Attachment' => isset($_GET['download'])));
    exit();
} else {
    // Preview mode - show HTML
    ?>
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>Payslips PDF Preview - OCP Construction</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" />
        <style>
            body {
                background-color: #f8f9fa;
                padding: 20px;
            }
            .preview-container {
                max-width: 1200px;
                margin: 0 auto;
            }
            .preview-header {
                background-color: white;
                border-radius: 10px;
                padding: 20px;
                margin-bottom: 20px;
                box-shadow: 0 2px 5px rgba(0,0,0,0.1);
            }
            .preview-actions {
                display: flex;
                gap: 10px;
                justify-content: flex-end;
            }
            .preview-content {
                background-color: white;
                border-radius: 10px;
                padding: 40px;
                box-shadow: 0 2px 10px rgba(0,0,0,0.1);
                min-height: 800px;
                overflow-x: auto;
            }
            .btn-preview {
                padding: 10px 20px;
                font-size: 16px;
            }
            .btn-download {
                background-color: #28a745;
                border-color: #28a745;
                color: white;
            }
            .btn-download:hover {
                background-color: #218838;
                border-color: #1e7e34;
                color: white;
            }
        </style>
    </head>
    <body>
        <div class="preview-container">
            <div class="preview-header d-flex justify-content-between align-items-center">
                <h2 class="mb-0">Payslips Preview</h2>
                <div class="preview-actions">
                    <a href="generate_payslip_pdf.php?<?php echo http_build_query($_GET); ?>&download=1" class="btn btn-success btn-preview">
                        <i class="fas fa-download"></i> Download PDF
                    </a>
                    <a href="javascript:window.print()" class="btn btn-primary btn-preview">
                        <i class="fas fa-print"></i> Print
                    </a>
                    <a href="payroll.php" class="btn btn-secondary btn-preview">
                        <i class="fas fa-arrow-left"></i> Back
                    </a>
                </div>
            </div>
            <div class="preview-content" style="font-family: \'Courier New\', Courier, monospace; font-size: 8.5pt;">
                <?php echo $html; ?>
            </div>
        </div>
        
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"></script>
    </body>
    </html>
    <?php
}
exit();
?>